.TH "XFA" "1" "14 December 2024" "Roland Baudin" ""
.SH "NAME"
xfa \- A simple archive viewer and extractor for X Window
.SH "SYNOPSIS"
\fBxfa\fP [\-h] [\-\-help] [\-v] [\-\-version] [\fIarchive filename\fP]
.SH "DESCRIPTION"
X File Archive (xfa) is a simple archive viewer and extractor, to be used with X File Explorer (xfe) or stand alone.
.SH "AUTHOR"
Roland Baudin <roland65@free.fr>.
.SH "OPTIONS"
xfa accepts the following options:
.TP 
.B \-h, \-\-help
Print the help screen and exit.
.TP 
.B \-v, \-\-version
Print xfe version information and exit.
.TP 
.B archive filename (tar.gz, tar.bz2, zip, ...)
Specifies the path to the archive file to open when starting xfa.


.SH "SEE ALSO"
.BR xfe (1), 
.BR xfi (1), 
.BR xfp (1), 
.BR xfw (1)
